name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for making an issue with this repo, Since this is your first time please look over the Pinned Issues to see if this issue was a major issue"
        pr-message: "Thanks for making a PR as it is your first time contributing please look over other PRs and branches to make sure this is already not added!"
